### ISSUE TITLE
Extension stopped working after switching to https

### ISSUE THREAD

**Issue by VOOM108** [Mar-tin-G/LocalUrlToText#12]
Titel says it all, after the forum was switched to https, the extension stopped working.

**Comment by Mar-tin-G** [comment]
@VOOM108 thanks for bringing this up, I'll look into it.

The extension relies on the phpBB function `generate_board_url()` to check for internal links. Could you maybe check that the value returned from that function is correct for your board?

**Comment by VOOM108** [comment]
In the ACP both the Board-URL as well as under Server and Domain has https enabled. Using htps ist set to "forced". Old http-links get mod_rewritten. Stil neither the old links nor new ones with https generate the text for local URLs. 

Is there another way to check what you mean`?

**Comment by Mar-tin-G** [comment]
@VOOM108 thanks, seems to all be just fine; I'll try to reproduce the problem locally. I will let you know if more information is needed.

**Comment by Mar-tin-G** [comment]
@VOOM108 I tested it, you're right: when going to *ACP* > *General* tab > *Server configuration* > *Server settings* and setting
- *Force server URL settings* to **Yes** 
- *Server protocol* to **"https://"**
- *Server port* to **443**

Then the extension does not recognize and replace any links. The reason is that in this case the board url generated via the function `generate_board_url()` looks like this:

```
https://localhost:443/phpbb
```

This does not match the links inside posts, which look like this (the port number is missing):

```
https://localhost/phpbb
```

Reading through the code of `generate_board_url()`, I noticed that inside that function another ACP setting is checked. After I enabled *ACP* > *General* tab > *Server configuration* > *Cookie settings* > *Cookie secure*, the generated board URL is correct (no port), and the extension is working again. Could you please check this?

---

Another issue is the handling of *old* links. If a user posted a link while the board was running with the **http** protocol, the link is saved as-is in the database: `http://board.com/viewtopic.php?t=123`.

When later changing the board to use the **https** protocol, the link inside the post in the database is *not* updated. So when the post is now viewed, the saved link has `http://…` and does not match the current board URL starting with `https://…`, and so is not handled by this extension.

What's your opinion on this issue, would it help handling these *old* links, allowing the extesion to replace their link text?

**Comment by VOOM108** [comment]
It would be perfect if the extension could keep both the old links and new ones working of course. But if it was either/or the new ones should be handled. 

I will check the setting if it helps... :)
